name = "ghl-bridge"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GHL_CP_LOCATION_ID = "VpL3sVe4Vb1ANBx9DOL6"
GHL_JUMPSTART_LOC_ID = "C6ALWYCMrzuUGZQWGS33"
GHL_BAILEY_LOC_ID = "1g6SSCGibOPFz5vLATNV"

# Secrets — set via: wrangler secret put SECRET_NAME
# GHL_CP_PIT
# GHL_BAILEY_PIT
# GHL_JUMPSTART_PIT
# GHL_AGENCY_PIT
